// Import camera icons
const cameraIcons = {
  // DIGITAL
  original: require('../src/assets/cameras/original.png'),
  grdr: require('../src/assets/cameras/grdr.png'),
  ccdr: require('../src/assets/cameras/ccdr.png'),
  collage: require('../src/assets/cameras/collage.png'),
  puli: require('../src/assets/cameras/puli.png'),
  fxnr: require('../src/assets/cameras/fxnr.png'),

  // VIDEO
  vclassic: require('../src/assets/cameras/vclassic.png'),
  originalv: require('../src/assets/cameras/originalv.png'),
  dam: require('../src/assets/cameras/dam.png'),
  '16mm': require('../src/assets/cameras/16mm.png'),
  '8mm': require('../src/assets/cameras/8mm.png'),
  vhs: require('../src/assets/cameras/vhs.png'),
  kino: require('../src/assets/cameras/kino.png'),
  instss: require('../src/assets/cameras/instss.png'),
  vfuns: require('../src/assets/cameras/vfuns.png'),
  dcr: require('../src/assets/cameras/dcr.png'),
  glow: require('../src/assets/cameras/glow.png'),
  slidep: require('../src/assets/cameras/slidep.png'),

  // VINTAGE 120
  sclassic: require('../src/assets/cameras/sclassic.png'),
  hoga: require('../src/assets/cameras/hoga.png'),
  s67: require('../src/assets/cameras/s67.png'),
  kv88: require('../src/assets/cameras/kv88.png'),

  // INST COLLECTION
  instc: require('../src/assets/cameras/instc.png'),
  instsq: require('../src/assets/cameras/instsq.png'),
  instsqc: require('../src/assets/cameras/instsqc.png'),
  pafr: require('../src/assets/cameras/pafr.png'),

  // VINTAGE 135
  dclassic: require('../src/assets/cameras/dclassic.png'),
  grf: require('../src/assets/cameras/grf.png'),
  ct2f: require('../src/assets/cameras/ct2f.png'),
  dexp: require('../src/assets/cameras/dexp.png'),
  nt16: require('../src/assets/cameras/nt16.png'),
  d3d: require('../src/assets/cameras/d3d.png'),
  '135ne': require('../src/assets/cameras/135ne.png'),
  dfuns: require('../src/assets/cameras/dfuns.png'),
  ir: require('../src/assets/cameras/ir.png'),
  classicu: require('../src/assets/cameras/classicu.png'),
  dqs: require('../src/assets/cameras/dqs.png'),
  fqsr: require('../src/assets/cameras/fqsr.png'),
  golf: require('../src/assets/cameras/golf.png'),
  cpm35: require('../src/assets/cameras/cmp35.png'),
  '135sr': require('../src/assets/cameras/135sr.png'),
  dhalf: require('../src/assets/cameras/dhalf.png'),
  dslide: require('../src/assets/cameras/dslide.png'),

  // Camera info icons
  photo: require('../src/assets/camera-info/photo.png'),
  video: require('../src/assets/camera-info/video.png'),
  filmNegatives: require('../src/assets/camera-info/film-negatives.png'),
  importPhotos: require('../src/assets/camera-info/import-photos.png'),
  videoPhotoLivephoto: require('../src/assets/camera-info/video-photo-livephoto.png'),

  // Accessory info icons
  ndFilter: require('../src/assets/accessory/ndfilter.png'),
  fisheyeF: require('../src/assets/accessory/fisheyef.png'),
  fisheyeW: require('../src/assets/accessory/fisheyew.png'),
  prism: require('../src/assets/accessory/prism.png'),
  flashC: require('../src/assets/accessory/flashc.png'),
  star: require('../src/assets/accessory/star.png'),
};

// Camera data organized by categories
export const cameraCategories = [
  {
    title: 'DIGITAL',
    cameras: [
      {
        id: 'original',
        name: 'Original',
        icon: cameraIcons.original,
        hasVideo: true,
        infoIcons: [
          cameraIcons.photo,
          cameraIcons.importPhotos,
          cameraIcons.filmNegatives,
        ],
      },
      {
        id: 'grdr',
        name: 'GRD R',
        icon: cameraIcons.grdr,
        hasVideo: true,
        infoIcons: [cameraIcons.photo, cameraIcons.filmNegatives],
      },
      {
        id: 'ccdr',
        name: 'CCD R',
        icon: cameraIcons.ccdr,
        hasVideo: true,
        infoIcons: [cameraIcons.photo, cameraIcons.filmNegatives],
      },
      {
        id: 'collage',
        name: 'Collage',
        icon: cameraIcons.collage,
        hasVideo: false,
        infoIcons: [cameraIcons.photo, cameraIcons.importPhotos],
      },
      {
        id: 'puli',
        name: 'Puli',
        icon: cameraIcons.puli,
        hasVideo: false,
        infoIcons: [cameraIcons.photo, cameraIcons.importPhotos],
      },
      {
        id: 'fxnr',
        name: 'FXN R',
        icon: cameraIcons.fxnr,
        hasVideo: true,
        infoIcons: [cameraIcons.photo, cameraIcons.filmNegatives],
      },
    ],
  },
  {
    title: 'VIDEO',
    cameras: [
      {
        id: 'vclassic',
        name: 'V Classic',
        icon: cameraIcons.vclassic,
        hasVideo: false,
        infoIcons: [cameraIcons.videoPhotoLivephoto, cameraIcons.filmNegatives],
      },
      {
        id: 'originalv',
        name: 'Original V',
        icon: cameraIcons.originalv,
        hasVideo: false,
        infoIcons: [cameraIcons.videoPhotoLivephoto],
      },
      {
        id: 'dam',
        name: 'DAM',
        icon: cameraIcons.dam,
        hasVideo: false,
        infoIcons: [cameraIcons.videoPhotoLivephoto],
      },
      {
        id: '16mm',
        name: '16mm',
        icon: cameraIcons['16mm'],
        hasVideo: false,
        infoIcons: [cameraIcons.videoPhotoLivephoto, cameraIcons.filmNegatives],
      },
      {
        id: '8mm',
        name: '8mm',
        icon: cameraIcons['8mm'],
        hasVideo: false,
        infoIcons: [cameraIcons.videoPhotoLivephoto, cameraIcons.filmNegatives],
      },
      {
        id: 'vhs',
        name: 'VHS',
        icon: cameraIcons.vhs,
        hasVideo: false,
        infoIcons: [cameraIcons.videoPhotoLivephoto, cameraIcons.filmNegatives],
      },
      {
        id: 'kino',
        name: 'Kino',
        icon: cameraIcons.kino,
        hasVideo: false,
        infoIcons: [cameraIcons.videoPhotoLivephoto, cameraIcons.filmNegatives],
      },
      {
        id: 'instss',
        name: 'Inst SS',
        icon: cameraIcons.instss,
        hasVideo: false,
        infoIcons: [cameraIcons.video, cameraIcons.filmNegatives],
      },
      {
        id: 'vfuns',
        name: 'V FunS',
        icon: cameraIcons.vfuns,
        hasVideo: false,
        infoIcons: [cameraIcons.videoPhotoLivephoto, cameraIcons.filmNegatives],
      },
      {
        id: 'dcr',
        name: 'DCR',
        icon: cameraIcons.dcr,
        hasVideo: false,
        infoIcons: [cameraIcons.videoPhotoLivephoto, cameraIcons.filmNegatives],
      },
      {
        id: 'glow',
        name: 'Glow',
        icon: cameraIcons.glow,
        hasVideo: false,
        infoIcons: [cameraIcons.videoPhotoLivephoto, cameraIcons.filmNegatives],
      },
      {
        id: 'slidep',
        name: 'Slide P',
        icon: cameraIcons.slidep,
        hasVideo: false,
        infoIcons: [cameraIcons.video, cameraIcons.filmNegatives],
      },
    ],
  },
  {
    title: 'VINTAGE 135',
    cameras: [
      {
        id: 'dclassic',
        name: 'D Classic',
        icon: cameraIcons.dclassic,
        hasVideo: false,
        infoIcons: [cameraIcons.photo, cameraIcons.importPhotos],
      },
      {
        id: 'grf',
        name: 'GR F',
        icon: cameraIcons.grf,
        hasVideo: false,
        infoIcons: [cameraIcons.photo, cameraIcons.importPhotos],
      },
      {
        id: 'ct2f',
        name: 'CT2F',
        icon: cameraIcons.ct2f,
        hasVideo: false,
        infoIcons: [cameraIcons.photo, cameraIcons.importPhotos],
      },
      {
        id: 'dexp',
        name: 'D Exp',
        icon: cameraIcons.dexp,
        hasVideo: false,
        infoIcons: [cameraIcons.photo, cameraIcons.importPhotos],
      },
      {
        id: 'nt16',
        name: 'NT16',
        icon: cameraIcons.nt16,
        hasVideo: false,
        infoIcons: [cameraIcons.photo, cameraIcons.importPhotos],
      },
      {
        id: 'd3d',
        name: 'D3D',
        icon: cameraIcons.d3d,
        hasVideo: false,
        infoIcons: [cameraIcons.photo, cameraIcons.importPhotos],
      },
      {
        id: '135ne',
        name: '135 NE',
        icon: cameraIcons['135ne'],
        hasVideo: false,
        infoIcons: [cameraIcons.photo, cameraIcons.importPhotos],
      },
      {
        id: 'dfuns',
        name: 'D FunS',
        icon: cameraIcons.dfuns,
        hasVideo: false,
        infoIcons: [cameraIcons.photo, cameraIcons.importPhotos],
      },
      {
        id: 'ir',
        name: 'IR',
        icon: cameraIcons.ir,
        hasVideo: false,
        infoIcons: [cameraIcons.photo, cameraIcons.importPhotos],
      },
      {
        id: 'classicu',
        name: 'Classic U',
        icon: cameraIcons.classicu,
        hasVideo: false,
        infoIcons: [cameraIcons.photo, cameraIcons.importPhotos],
      },
      {
        id: 'dqs',
        name: 'DQS',
        icon: cameraIcons.dqs,
        hasVideo: false,
        infoIcons: [cameraIcons.photo, cameraIcons.importPhotos],
      },
      {
        id: 'fqsr',
        name: 'FQS R',
        icon: cameraIcons.fqsr,
        hasVideo: false,
        infoIcons: [cameraIcons.photo, cameraIcons.importPhotos],
      },
      {
        id: 'golf',
        name: 'Golf',
        icon: cameraIcons.golf,
        hasVideo: false,
        infoIcons: [cameraIcons.video, cameraIcons.importPhotos],
      },
      {
        id: 'cpm35',
        name: 'CPM35',
        icon: cameraIcons.cpm35,
        hasVideo: false,
        infoIcons: [cameraIcons.photo, cameraIcons.importPhotos],
      },
      {
        id: '135sr',
        name: '135 SR',
        icon: cameraIcons['135sr'],
        hasVideo: false,
        infoIcons: [
          cameraIcons.photo,
          cameraIcons.filmNegatives,
          cameraIcons.importPhotos,
        ],
      },
      {
        id: 'dhalf',
        name: 'D Half',
        icon: cameraIcons.dhalf,
        hasVideo: false,
        infoIcons: [cameraIcons.photo, cameraIcons.importPhotos],
      },
      {
        id: 'dslide',
        name: 'D Slide',
        icon: cameraIcons.dslide,
        hasVideo: false,
        infoIcons: [cameraIcons.photo, cameraIcons.importPhotos],
      },
    ],
  },
  {
    title: 'VINTAGE 120',
    cameras: [
      {
        id: 'sclassic',
        name: 'S Classic',
        icon: cameraIcons.sclassic,
        hasVideo: false,
        infoIcons: [cameraIcons.photo, cameraIcons.importPhotos],
      },
      {
        id: 'hoga',
        name: 'HOGA',
        icon: cameraIcons.hoga,
        hasVideo: false,
        infoIcons: [cameraIcons.photo, cameraIcons.importPhotos],
      },
      {
        id: 's67',
        name: 'S 67',
        icon: cameraIcons.s67,
        hasVideo: false,
        infoIcons: [cameraIcons.photo, cameraIcons.importPhotos],
      },
      {
        id: 'kv88',
        name: 'KV88',
        icon: cameraIcons.kv88,
        hasVideo: true,
        infoIcons: [
          cameraIcons.photo,
          cameraIcons.importPhotos,
          cameraIcons.filmNegatives,
        ],
      },
    ],
  },
  {
    title: 'INST COLLECTION',
    cameras: [
      {
        id: 'instc',
        name: 'Inst C',
        icon: cameraIcons.instc,
        hasVideo: true,
        infoIcons: [
          cameraIcons.photo,
          cameraIcons.importPhotos,
          cameraIcons.filmNegatives,
        ],
      },
      {
        id: 'instsq',
        name: 'Inst SQ',
        icon: cameraIcons.instsq,
        hasVideo: false,
        infoIcons: [cameraIcons.photo, cameraIcons.importPhotos],
      },
      {
        id: 'instsqc',
        name: 'Inst SQC',
        icon: cameraIcons.instsqc,
        hasVideo: false,
        infoIcons: [cameraIcons.photo, cameraIcons.importPhotos],
      },
      {
        id: 'pafr',
        name: 'PAF R',
        icon: cameraIcons.pafr,
        hasVideo: true,
        infoIcons: [cameraIcons.photo, cameraIcons.filmNegatives],
      },
    ],
  },
  {
    title: 'ACCESSORY',
    accessories: [
      {
        id: 'ndfilter',
        name: 'ND Filter',
        icon: cameraIcons.ndFilter,
        hasVideo: false,
      },
      {
        id: 'fisheyef',
        name: 'Fisheye F',
        icon: cameraIcons.fisheyeF,
        hasVideo: false,
      },
      {
        id: 'fisheyew',
        name: 'Fisheye W',
        icon: cameraIcons.fisheyeW,
        hasVideo: false,
      },
      {id: 'prism', name: 'Prism', icon: cameraIcons.prism, hasVideo: false},
      {
        id: 'flashc',
        name: 'Flash C',
        icon: cameraIcons.flashC,
        hasVideo: false,
      },
      {id: 'star', name: 'Star', icon: cameraIcons.star, hasVideo: false},
    ],
  },
];

export {cameraIcons};
